### ISSUE TITLE
New Feature Request - DRG Route Table - Static Route Rules

### ISSUE THREAD

**Issue by Kamil-Stachura** [oracle-quickstart/terraform-oci-cis-landing-zone-networking#1]
Hi Team,

Please consider implementing the logic to define static route rules in the DRG route tables. 

https://registry.terraform.io/providers/oracle/oci/latest/docs/resources/core_drg_route_table_route_rule

The purpose of this is to, for example, direct the traffic via a FW located in a hub VCN, when using a hub & spoke topology.

Thank you in advance!

**Comment by cosmindev** [comment]
Solved under v0.2.0
