### ISSUE TITLE
Internet Gateway Route Table - Route Rule Next Hop Doesn't Accept "network_entity_key"

### ISSUE THREAD

**Issue by Kamil-Stachura** [oracle-quickstart/terraform-oci-cis-landing-zone-networking#4]
Hi Team,

A VCN route table assigned to an Internet Gateway has to specify a private IP ID as the next hop within its route rules, just like when referencing NFWs as the next hop.

However when trying to assign a route table to an Internet Gateway that specifies a NFW as the "network_entity_key" within a route rule, I'm presented with the following error:

```
Planning failed. Terraform encountered an error while generating this plan.
╷
│ Error: Missing required argument
│ 
│   with module.terraform-oci-cis-landing-zone-network.oci_core_route_table.these_gw_attached["RT_VCN_UKS_HUB_P_IGW"],
│   on .terraform/modules/terraform-oci-cis-landing-zone-network/route_tables.tf line 226, in resource "oci_core_route_table" "these_gw_attached":
│  226: resource "oci_core_route_table" "these_gw_attached" {
│ 
│ The argument "route_rules.0.network_entity_id" is required,
│ but no definition was found.
```

I was only able to attach the route table to the IGW using the modules if it had no route rules or the "network_entity_id" was used with the NFW's Private IP OCID.

This points me to think that the oci_core_route_table.these_gw_attached currently doesn't support looking up the Private IP OCID of the next hop based on the "network_entity_key".

Please consider implementing this functionality or recommend an alternative solution.

Thank you in advance!

**Comment by cosmindev** [comment]
Fixed in version 0.5.1
